image: python:3.9-alpine

pages:
  stage: deploy
  # ğŸ”¥ æ–°å¢é€™è£¡ï¼šæŒ‡åè¦ç”¨æœ‰ "tejapi" æ¨™ç±¤çš„æ©Ÿå™¨äºº
  tags:
    - tejapi
    
  script:
    - pip install mkdocs-material
    - mkdocs build -f config/zh-TW/mkdocs.yml -d public
  artifacts:
    paths:
      - public
  only:
    - main
    - feature/ci-setup 