image: python:3.9-alpine

pages:
  stage: deploy
  script:
    - pip install mkdocs-material
    - mkdocs build -f config/zh-TW/mkdocs.yml -d public
  artifacts:
    paths:
      - public
  only:
    - main
    - feature/ci-setup