image: python:3.9-alpine

pages:
  stage: deploy
  tags:
    - windows-runner  # 請改成你剛剛在網頁上設定的 Tag
  script:
    - pip install mkdocs-material  # 確保你的電腦有裝這個
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  only:
    - main